version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://urlshort:secret@mysql:3306/urlshortener?serverVersion=5.7
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: urlshortener
            MYSQL_USER: urlshort
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - symfony
networks:
    symfony:
