security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
          entity:
              class: App\Entity\User
              property: username

    firewalls:
        # dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        private:
            pattern: ^/api/url
            methods: ['POST']
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                  - lexik_jwt_authentication.jwt_token_authenticator

        public:
            pattern: ^/api
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/api/url, roles: IS_AUTHENTICATED_FULLY, methods: ['POST'] }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
